name: python-test

on:
  schedule:
    # - cron: "0 3 * * *"
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run test_main.py
        run: |
          python test_main.py
      - name: commit and push to data
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.email "***@***.com"
          git config --global user.name "github workflow"
          git checkout data
          git add .
          git commit -m "auto-data"
          git pull
          git push origin data
