name: python-test

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9.6
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run test_main.py
        run: |
          python test_main.py
      - name: commit and push to data
        env:
          TZ: "Asia/Tokyo"
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.email "***@***.com"
          git config --global user.name "github workflow"
          # git checkout data
          git add .
          DATE=`date +"%Y%m%dT%H:%M:%S"`
          git commit -m "$DATE"
          # git pull
          git push origin main
